import type { StoryDefinition } from '../domain/types';

export const storyCatalog: readonly StoryDefinition[] = [
  {
    id: "CB-ACCOUNT-001",
    title: "Create an account",
    sourceDiagram: "Create Account.drawio",
    actor: "Prospective Cipherbank user",
    userStory: "As a prospective cipherbank user, I want to create a Cipherbank account and establish a recoverable encrypted user-data record so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Signed out", "Create-account page available"],
    steps: [
      { id: "open", action: "Open the create-account page.", expected: "The account form is visible.", service: "No write request occurs." },
      { id: "complete-form", action: "Enter required account information and accept required agreements.", expected: "Invalid or missing values are identified before submission.", service: "No account is created while validation errors remain." },
      { id: "submit", action: "Submit the account form.", expected: "A single in-progress state is shown.", service: "Exactly one account-creation request is sent." },
      { id: "backup", action: "Complete the recovery-secret or backup step.", expected: "Recovery material appears only in the protected flow.", service: "An encrypted user backup is created." },
      { id: "complete", action: "Finish account creation.", expected: "Success and an authenticated destination are shown.", service: "Account and initialized user metadata persist." },
    ],
    successCriteria: ["Exactly one account exists", "Authenticated session belongs to the new account"],
    negativeCases: ["Duplicate identifier", "Weak credentials", "Backup failure", "Network retry is idempotent"],
  },
  {
    id: "CB-ACCOUNT-002",
    title: "Recover an account",
    sourceDiagram: "Recover Account.drawio",
    actor: "Existing Cipherbank user",
    userStory: "As a existing cipherbank user, I want to recover an account from recovery material and encrypted backup so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Signed out", "Valid backup exists"],
    steps: [
      { id: "open", action: "Open account recovery.", expected: "The recovery form is visible without account enumeration.", service: "No account data is fetched yet." },
      { id: "enter", action: "Enter account identifier and recovery material.", expected: "Secret format is validated without logging it.", service: "Recovery material remains protected." },
      { id: "submit", action: "Submit recovery.", expected: "One recovery attempt is shown as in progress.", service: "Encrypted backup is requested." },
      { id: "restore", action: "Unlock the backup and enroll the device if required.", expected: "Restored account information appears only after authorization.", service: "Wallet references and account state are restored." },
      { id: "complete", action: "Enter the recovered account.", expected: "Authenticated navigation and restored metadata are visible.", service: "Recovered session maps to the original account." },
    ],
    successCriteria: ["Original account is restored", "No replacement wallets are created unexpectedly"],
    negativeCases: ["Invalid recovery material", "Rate limiting", "Corrupt backup", "Backup service unavailable"],
  },
  {
    id: "CB-WALLET-001",
    title: "Create a user-controlled wallet",
    sourceDiagram: "Create Wallet (User).drawio",
    actor: "Authenticated Cipherbank user",
    userStory: "As a authenticated cipherbank user, I want to create a non-custodial user-controlled savings/vault wallet so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Authenticated", "Supported network enabled"],
    steps: [
      { id: "open", action: "Open Wallets and choose Create wallet.", expected: "Wallet type selection is visible.", service: "No wallet exists yet." },
      { id: "type", action: "Choose User-controlled / Vault.", expected: "Non-custodial behavior is disclosed.", service: "Custody mode is user-controlled." },
      { id: "details", action: "Choose a network and label.", expected: "Only supported networks and valid labels continue.", service: "Creation is scoped to one user and network." },
      { id: "generate", action: "Generate the wallet.", expected: "Public address and protected recovery step appear.", service: "Only public metadata/encrypted backup references leave the user boundary." },
      { id: "confirm", action: "Confirm recovery material.", expected: "Wallet is not ready until confirmation succeeds.", service: "Private signing material is not server-accessible." },
      { id: "finish", action: "Finish.", expected: "Wallet card shows label, network, address, zero balance, and User-controlled badge.", service: "Wallet metadata persists exactly once." },
    ],
    successCriteria: ["One user-controlled wallet is created", "No private material appears in API payloads"],
    negativeCases: ["Abandoned recovery", "Duplicate submission", "Unsupported network"],
  },
  {
    id: "CB-WALLET-002",
    title: "Create a Cipherbank checking wallet",
    sourceDiagram: "Create Wallet (CB).drawio",
    actor: "Authenticated Cipherbank user",
    userStory: "As a authenticated cipherbank user, I want to create a Cipherbank checking wallet with hybrid custody so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Authenticated", "Eligible for checking wallet"],
    steps: [
      { id: "open", action: "Open Wallets and choose Create wallet.", expected: "Wallet type selection is visible.", service: "No write occurs." },
      { id: "type", action: "Choose Cipherbank / Checking.", expected: "Hybrid signing behavior is disclosed.", service: "Custody mode is hybrid." },
      { id: "details", action: "Choose a network and label.", expected: "Only supported networks can continue.", service: "The network adapter is selected." },
      { id: "generate", action: "Submit wallet creation.", expected: "One in-progress state is shown.", service: "Wallet service creates against the selected node." },
      { id: "policy", action: "Complete user-key enrollment or policy approval.", expected: "Wallet is not active until policy establishment succeeds.", service: "Wallet DB stores hybrid policy metadata." },
      { id: "finish", action: "Finish.", expected: "Wallet card shows Checking and Hybrid badges.", service: "Node and database wallet identities agree." },
    ],
    successCriteria: ["One hybrid wallet is created", "Required signing policy is attached"],
    negativeCases: ["Node failure", "Policy failure", "Duplicate retry"],
  },
  {
    id: "CB-FUND-001",
    title: "Fund a user-controlled wallet",
    sourceDiagram: "Fund Wallet (User).drawio",
    actor: "Authenticated Cipherbank user",
    userStory: "As a authenticated cipherbank user, I want to receive funds into a user-controlled wallet and observe confirmations so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["User wallet exists", "Network fixture available"],
    steps: [
      { id: "open", action: "Open the wallet and choose Fund / Receive.", expected: "Receive view shows the correct wallet and network.", service: "Wallet record is loaded." },
      { id: "address", action: "Reveal the deposit address.", expected: "Address text and QR representation match.", service: "Address belongs to the selected wallet." },
      { id: "send", action: "Send test funds with a network fixture.", expected: "A single detected/pending deposit appears.", service: "The network event is observed." },
      { id: "confirm", action: "Advance network confirmations.", expected: "Pending balance and confirmation count update deterministically.", service: "Transaction state transitions persist." },
      { id: "spendable", action: "Reach the spendable threshold.", expected: "Available balance and one activity row update.", service: "Confirmed ledger and UI state reconcile." },
    ],
    successCriteria: ["Pending and available balances are distinct", "Replayed events do not duplicate credit"],
    negativeCases: ["Wrong network", "Reorg", "Network outage"],
  },
  {
    id: "CB-FUND-002",
    title: "Fund a Cipherbank checking wallet",
    sourceDiagram: "Fund Wallet (CB).drawio",
    actor: "Authenticated Cipherbank user",
    userStory: "As a authenticated cipherbank user, I want to receive funds into a Cipherbank checking wallet so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Checking wallet exists", "Node available"],
    steps: [
      { id: "open", action: "Open the checking wallet and choose Fund / Receive.", expected: "Receive view identifies Checking / Hybrid custody.", service: "Wallet record is loaded." },
      { id: "address", action: "Reveal the deposit address.", expected: "Address and QR match the selected network.", service: "Wallet module resolves the receiving address." },
      { id: "send", action: "Send test funds.", expected: "One pending incoming transaction appears.", service: "Node detects the transaction." },
      { id: "confirm", action: "Advance confirmations.", expected: "Pending, confirmed, and available values update correctly.", service: "Canonical states persist." },
      { id: "activity", action: "Open Activity.", expected: "Deposit row shows amount, network, identifier, timestamp, and status.", service: "Activity and balance reconcile." },
    ],
    successCriteria: ["Confirmed amount becomes available", "Duplicate notifications do not duplicate credit"],
    negativeCases: ["Node outage", "Reorg/replacement"],
  },
  {
    id: "CB-CARD-001",
    title: "Create a prepaid card from an account",
    sourceDiagram: "Create Prepaid Card (Account).drawio",
    actor: "Authenticated Cipherbank user",
    userStory: "As a authenticated cipherbank user, I want to create and fund a prepaid card from a wallet so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Authenticated", "Eligible funded wallet exists"],
    steps: [
      { id: "open", action: "Open Cards and choose Create prepaid card.", expected: "Card creation form is visible.", service: "No card exists yet." },
      { id: "details", action: "Choose source wallet, asset, card currency, and amount.", expected: "Balance and limits are visible.", service: "Wallet availability is verified." },
      { id: "quote", action: "Request a quote.", expected: "Rate, fees, card value, crypto amount, and expiry are visible.", service: "Cached/provider market quote is obtained." },
      { id: "confirm", action: "Confirm before quote expiry.", expected: "One processing state is shown.", service: "Funds are reserved or debited once." },
      { id: "step-up", action: "Complete any step-up/signing approval.", expected: "Card issuance cannot continue before required approval.", service: "Policy result attaches to the transaction." },
      { id: "issued", action: "Wait for issuance.", expected: "Masked card details, status, and funded balance appear.", service: "Card network and user-card records update." },
      { id: "activity", action: "Open Activity.", expected: "One card creation/funding row is shown.", service: "Interaction and transaction history records persist." },
    ],
    successCriteria: ["Source wallet debited once", "Card value reconciles to quote and fees"],
    negativeCases: ["Expired quote", "Insufficient balance", "Card-network failure", "Duplicate submit", "Security/compliance review"],
  },
  {
    id: "CB-CARD-002",
    title: "Create a prepaid card as a guest",
    sourceDiagram: "Create Prepaid Card (Guest).drawio",
    actor: "Guest user",
    userStory: "As a guest user, I want to exchange supported cryptocurrency for a guest prepaid card so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Signed out", "Guest card flow enabled"],
    steps: [
      { id: "open", action: "Open guest card creation.", expected: "Guest limitations are disclosed.", service: "Temporary guest transaction identity is created." },
      { id: "details", action: "Choose source asset, card currency, and amount.", expected: "Supported assets and limits are visible.", service: "No persistent account is created." },
      { id: "quote", action: "Request a quote.", expected: "Rate, fees, amount due, card value, and expiry are visible.", service: "Market quote is obtained." },
      { id: "payment", action: "Confirm and obtain payment instructions.", expected: "Address and QR match the selected network and quote.", service: "Temporary receiving path is prepared." },
      { id: "confirmations", action: "Send crypto and advance network state.", expected: "Status moves awaiting \u2192 detected \u2192 confirmed.", service: "Selected network confirms payment." },
      { id: "issued", action: "Receive the card.", expected: "Masked card, balance, status, and guest retrieval mechanism appear.", service: "One guest card is issued." },
    ],
    successCriteria: ["No persistent account is created", "Exactly one card is issued"],
    negativeCases: ["Under/overpayment", "Late payment", "Wrong network", "Expired quote", "Reload/resume", "Issuance failure"],
  },
  {
    id: "CB-PAY-001",
    title: "Pay a merchant from a user-controlled wallet",
    sourceDiagram: "Pay Merchent (User Wallet).drawio",
    actor: "Authenticated Cipherbank user",
    userStory: "As a authenticated cipherbank user, I want to pay a merchant from a user-controlled wallet so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Authenticated", "Funded user wallet exists"],
    steps: [
      { id: "start", action: "Start merchant payment.", expected: "Merchant, amount, currency, and source are visible.", service: "Canonical payment transaction is created." },
      { id: "source", action: "Select the user-controlled wallet.", expected: "Balance and custody mode are shown.", service: "Selected wallet is resolved." },
      { id: "quote", action: "Request or receive a conversion quote.", expected: "Crypto debit, merchant amount, rate, fees, and expiry are visible.", service: "Market data is obtained." },
      { id: "authorize", action: "Authorize with the user signing method.", expected: "Payment cannot continue without valid authorization.", service: "Private signing material remains user-controlled." },
      { id: "submit", action: "Submit the authorized payment.", expected: "One processing state is shown.", service: "Network broadcast and merchant settlement are initiated." },
      { id: "result", action: "Receive the outcome.", expected: "A canonical outcome is displayed.", service: "Transaction reaches a defined state." },
      { id: "activity", action: "Open Activity.", expected: "One reconciled merchant payment row appears.", service: "Transaction history updates." },
    ],
    successCriteria: ["Wallet debit and merchant settlement reconcile", "Signing secret remains private"],
    negativeCases: ["Expired quote", "Insufficient balance", "Invalid signature", "Compliance denial", "Broadcast failure", "Reload during processing"],
  },
  {
    id: "CB-PAY-002",
    title: "Pay a merchant from a Cipherbank checking wallet",
    sourceDiagram: "Pay Merchent (CB Wallet).drawio",
    actor: "Authenticated Cipherbank user",
    userStory: "As a authenticated cipherbank user, I want to pay a merchant under the hybrid user-and-Cipherbank signing policy so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Authenticated", "Funded checking wallet exists", "Co-signing path healthy"],
    steps: [
      { id: "start", action: "Start merchant payment.", expected: "Merchant, amount, currency, and source are visible.", service: "Canonical payment is created." },
      { id: "source", action: "Select the Cipherbank checking wallet.", expected: "Checking / Hybrid custody and balance are shown.", service: "Wallet and key policy are resolved." },
      { id: "quote", action: "Review the quote.", expected: "Rate, expiry, debit, merchant amount, and fees are shown.", service: "Market data is obtained." },
      { id: "user-approval", action: "Approve the user side.", expected: "Final approval is not displayed prematurely.", service: "User approval attaches to the transaction." },
      { id: "cb-approval", action: "Complete Cipherbank co-sign/policy.", expected: "Step-up, review, denial, or approval is visible.", service: "Cipherbank policy validates and co-signs." },
      { id: "settle", action: "Broadcast and settle.", expected: "One processing transaction is shown.", service: "Node and merchant settlement paths execute." },
      { id: "result", action: "Receive result and open Activity.", expected: "Receipt and activity reconcile.", service: "Wallet, history, backup metadata, and tracking update." },
    ],
    successCriteria: ["Both authorization sides precede settlement", "Wallet is debited once"],
    negativeCases: ["Missing user approval", "Co-sign unavailable", "Expired quote", "Settlement failure"],
  },
  {
    id: "CB-PAY-003",
    title: "Pay a merchant with a prepaid card",
    sourceDiagram: "Pay Merchent (Prepayed).drawio",
    actor: "Prepaid card holder",
    userStory: "As a prepaid card holder, I want to pay a merchant at POS using a prepaid card so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Active funded prepaid card exists", "POS fixture available"],
    steps: [
      { id: "present", action: "Present the card through the supported POS/RFID path.", expected: "Merchant and purchase amount are displayed.", service: "One authorization request is received." },
      { id: "authorize", action: "Submit authorization.", expected: "Request enters pending once.", service: "Card status and available balance are validated." },
      { id: "verify", action: "Apply required card verification.", expected: "Invalid, blocked, expired, or insufficient cards fail distinctly.", service: "Card controls are enforced." },
      { id: "result", action: "Receive authorization result.", expected: "POS and Cipherbank views agree.", service: "Approved balance update is atomic." },
      { id: "receipt", action: "View card balance and receipt.", expected: "Balance decreases exactly once and one receipt appears.", service: "Transaction persists once." },
    ],
    successCriteria: ["Purchase is authorized once", "POS result and card ledger agree"],
    negativeCases: ["Insufficient balance", "Blocked/expired card", "Duplicate authorization", "Timeout/reconciliation"],
  },
  {
    id: "CB-MARKET-001",
    title: "View current and historical price data",
    sourceDiagram: "View Price Data.drawio",
    actor: "Cipherbank visitor or user",
    userStory: "As a cipherbank visitor or user, I want to view fresh current and historical cryptocurrency market data so that I can complete the Cipherbank workflow safely and verifiably.",
    preconditions: ["Market page available", "Provider or cache data exists"],
    steps: [
      { id: "open", action: "Open the market-data page.", expected: "Asset, quote currency, current price, chart, and freshness controls are visible.", service: "Current data is requested." },
      { id: "select", action: "Select asset and quote currency.", expected: "Selection is reflected in UI state.", service: "Correct market pair is requested." },
      { id: "current", action: "View the current price.", expected: "Price, source, and as-of timestamp are shown.", service: "Cache/provider data is served." },
      { id: "history", action: "Select a historical range.", expected: "Chart/table updates without mixing assets.", service: "Historical database supplies the series." },
      { id: "freshness", action: "Refresh or exceed freshness threshold.", expected: "Fresh, cached, stale, and unavailable states are distinguishable.", service: "Provider fallback follows cache policy." },
    ],
    successCriteria: ["Values match selected pair/range", "Source time is not misrepresented"],
    negativeCases: ["Provider failover", "All providers unavailable", "Historical gaps", "Rapid asset switching race"],
  },
  {
    id: 'CB-PREPAID-PLACEHOLDER',
    title: 'Make a prepaid purchase — source flow missing',
    sourceDiagram: 'Make Prepaid Purchase.drawio',
    actor: 'Undetermined',
    userStory: 'The uploaded source diagram is blank and cannot yet define an authoritative workflow.',
    preconditions: [], steps: [], successCriteria: [],
    negativeCases: ['Determine whether this duplicates prepaid-card merchant payment or means purchasing a prepaid card.'],
  },
] as const;

export function story(id: string): StoryDefinition {
  const found = storyCatalog.find((item) => item.id === id);
  if (!found) throw new Error(`Unknown Cipherbank story: ${id}`);
  return found;
}