// <auto-generated />
using CipherBank_app.Persist;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CipherBank_app.Persist.Migrations
{
    [DbContext(typeof(CipherBankDbContext))]
    partial class CipherBankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("CipherBank_app.Persist.Entities.OhlcPointEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("t");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("v");

                    b.HasKey("Symbol", "Timestamp");

                    b.ToTable("ohlc", (string)null);
                });

            modelBuilder.Entity("CipherBank_app.Persist.Entities.PreferenceEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("prefs", (string)null);
                });

            modelBuilder.Entity("CipherBank_app.Persist.Entities.RateSnapshotEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<decimal>("Change24H")
                        .HasColumnType("TEXT")
                        .HasColumnName("change24h");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Usd")
                        .HasColumnType("TEXT")
                        .HasColumnName("usd");

                    b.HasKey("Symbol");

                    b.ToTable("rates_snapshot", (string)null);
                });

            modelBuilder.Entity("CipherBank_app.Persist.Entities.RecipientEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountMask")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_mask");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_type");

                    b.Property<string>("Bank")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Holder")
                        .HasColumnType("TEXT")
                        .HasColumnName("holder");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT")
                        .HasColumnName("memo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RoutingMask")
                        .HasColumnType("TEXT")
                        .HasColumnName("routing_mask");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("recipients", (string)null);
                });

            modelBuilder.Entity("CipherBank_app.Persist.Entities.SyncMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("sync_meta", (string)null);
                });

            modelBuilder.Entity("CipherBank_app.Persist.Entities.WalletEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AccountIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_index");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.ToTable("wallets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
